package baitaplon.view;

import baitaplon.utils.SessionManager;
import java.util.List;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Dialog chọn nhân viên để bắt đầu ca làm việc
 */
public class EmployeeSelectionDialog extends javax.swing.JDialog {
    
    private static final Logger logger = LoggerFactory.getLogger(EmployeeSelectionDialog.class);
    private SessionManager sessionManager;
    private boolean sessionStarted = false;
    
    /**
     * Creates new form EmployeeSelectionDialog
     */
    public EmployeeSelectionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        sessionManager = SessionManager.getInstance();
        initComponents();
        setupUI();
        loadEmployees();
    }
    
    private void setupUI() {
        setTitle("Chọn nhân viên - Bắt đầu ca làm việc");
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        
        // Style title
        titleLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        titleLabel.setForeground(new java.awt.Color(70, 130, 180));
        
        // Style buttons
        startSessionButton.setBackground(new java.awt.Color(46, 204, 113));
        startSessionButton.setForeground(java.awt.Color.WHITE);
        startSessionButton.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        
        cancelButton.setBackground(new java.awt.Color(231, 76, 60));
        cancelButton.setForeground(java.awt.Color.WHITE);
        cancelButton.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        
        // Style table
        employeesTable.getTableHeader().setBackground(new java.awt.Color(70, 130, 180));
        employeesTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        employeesTable.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        employeesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void loadEmployees() {
        try {
            List<Object[]> employees = sessionManager.getAllEmployees();
            if (employees == null) {
                JOptionPane.showMessageDialog(this, "Không thể tải danh sách nhân viên!", 
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) employeesTable.getModel();
            model.setRowCount(0);
            
            for (Object[] emp : employees) {
                if (emp.length >= 2) {
                    model.addRow(new Object[]{
                        emp[0], // ID
                        emp[1]  // Tên nhân viên
                    });
                }
            }
            
        } catch (Exception e) {
            logger.error("Error loading employees", e);
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách nhân viên: " + e.getMessage(), 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public boolean isSessionStarted() {
        return sessionStarted;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();
        startSessionButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        titleLabel.setText("CHỌN NHÂN VIÊN ĐỂ BẮT ĐẦU CA LÀM VIỆC");

        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên nhân viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeesTable);

        startSessionButton.setText("Bắt đầu ca");
        startSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSessionButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Hủy");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startSessionButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startSessionButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSessionButtonActionPerformed
        int selectedRow = employeesTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên!", 
                "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Integer employeeId = (Integer) employeesTable.getValueAt(selectedRow, 0);
        String employeeName = (String) employeesTable.getValueAt(selectedRow, 1);
        
        if (sessionManager.startSession(employeeId)) {
            sessionStarted = true;
            JOptionPane.showMessageDialog(this, 
                "Đã bắt đầu ca làm việc cho nhân viên: " + employeeName, 
                "Thành công", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Không thể bắt đầu ca làm việc!", 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_startSessionButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTable employeesTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton startSessionButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
