/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitaplon;

/**
 *
 * @author HI
 */
import baitaplon.view.*;
public class main_layout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(main_layout.class.getName());

     // === NEW === CardLayout + main panel + các màn hình con
    private java.awt.CardLayout card;
    private static final String CARD_THONGKE = "THONGKE";
    private static final String CARD_BANHANG = "BANHANG";
    private static final String CARD_NHAPHANG = "NHAPHANG";
    private static final String CARD_LICHSU   = "LICHSU";
    private static final String CARD_QUANLYSANPHAM = "QUANLYSANPHAM";
    public main_layout() {
        initComponents();
        initCards();
        bindMenuActions();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu5.setText("Thống kê");
        jMenuBar1.add(jMenu5);

        jMenu1.setText("Bán hàng");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Nhập hàng");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Lịch sử");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Quản lý sản phẩm");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // === NEW === Tạo CardLayout + các màn hình con
    private baitaplon.view.banhang pnlbanhang;
    private baitaplon.view.lichsu pnllichsu;
    private baitaplon.view.nhaphang pnlnhaphang;
    private baitaplon.view.thongke pnlthongke;
    private baitaplon.view.QuanLySanPham pnlquanlysanpham;
    private void initCards() {
        // đảm bảo layout là CardLayout
        card = new java.awt.CardLayout();
        mainPanel.setLayout(card);
        pnlbanhang = new banhang();
        pnllichsu = new lichsu();
        pnlnhaphang = new nhaphang();
        pnlthongke = new thongke();
        pnlquanlysanpham = new QuanLySanPham();
        

        // nạp các panel con (mỗi panel là 1 file riêng)
        mainPanel.add(pnlthongke, CARD_THONGKE);
        mainPanel.add(pnlbanhang, CARD_BANHANG);
        mainPanel.add(pnlnhaphang, CARD_NHAPHANG);
        mainPanel.add(pnllichsu,  CARD_LICHSU);
        mainPanel.add(pnlquanlysanpham, CARD_QUANLYSANPHAM);

        card.show(mainPanel, CARD_THONGKE); // trang mặc định
    }

    // === NEW === Gán sự kiện cho menu (click vào JMenu là đổi trang)
    private void bindMenuActions() {
        // Khuyến nghị: dùng JMenuItem. Nếu bạn đang dùng JMenu, có thể MouseListener như sau:
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mousePressed(java.awt.event.MouseEvent e) {
                card.show(mainPanel, CARD_THONGKE);
            }
        });
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mousePressed(java.awt.event.MouseEvent e) {
                card.show(mainPanel, CARD_BANHANG);
            }
        });
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mousePressed(java.awt.event.MouseEvent e) {
                card.show(mainPanel, CARD_NHAPHANG);
            }
        });
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mousePressed(java.awt.event.MouseEvent e) {
                card.show(mainPanel, CARD_LICHSU);
            }
        });
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mousePressed(java.awt.event.MouseEvent e) {
                card.show(mainPanel, CARD_QUANLYSANPHAM);
            }
        });
    }

    // === NEW === Setup UI improvements
    private void setupUI() {
        // Set window properties
        setTitle("Baitaplon - Hệ thống quản lý thu chi quán cafe");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        // Set menu styling
        jMenuBar1.setBackground(new java.awt.Color(70, 130, 180));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        
        // Style menu items
        styleMenuItem(jMenu1);
        styleMenuItem(jMenu2);
        styleMenuItem(jMenu3);
        styleMenuItem(jMenu4);
        styleMenuItem(jMenu5);
        
        // Set main panel background
        mainPanel.setBackground(new java.awt.Color(248, 249, 250));
        
        // Add status bar
        addStatusBar();
    }
    
    private void styleMenuItem(javax.swing.JMenu menu) {
        menu.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        menu.setForeground(java.awt.Color.WHITE);
        menu.setOpaque(false);
        menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
    }
    
    private void addStatusBar() {
        javax.swing.JPanel statusPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        statusPanel.setBackground(new java.awt.Color(240, 240, 240));
        statusPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, java.awt.Color.GRAY),
            javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
        
        javax.swing.JLabel statusLabel = new javax.swing.JLabel("Sẵn sàng");
        statusLabel.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        statusPanel.add(statusLabel, java.awt.BorderLayout.WEST);
        
        javax.swing.JLabel timeLabel = new javax.swing.JLabel();
        timeLabel.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        updateTimeLabel(timeLabel);
        statusPanel.add(timeLabel, java.awt.BorderLayout.EAST);
        
        // Add timer to update time
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> updateTimeLabel(timeLabel));
        timer.start();
        
        add(statusPanel, java.awt.BorderLayout.SOUTH);
    }
    
    private void updateTimeLabel(javax.swing.JLabel timeLabel) {
        java.time.ZoneId vietnamZone = java.time.ZoneId.of("Asia/Ho_Chi_Minh");
        java.time.LocalDateTime now = java.time.LocalDateTime.now(vietnamZone);
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        timeLabel.setText(now.format(formatter));
    }
    
    // === NEW === Helper tạo trang demo nhanh
    private javax.swing.JPanel makeSimplePage(String title) {
        javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.BorderLayout());
        javax.swing.JLabel lb = new javax.swing.JLabel(title, javax.swing.SwingConstants.CENTER);
        lb.setFont(lb.getFont().deriveFont(18f));
        p.add(lb, java.awt.BorderLayout.CENTER);
        return p;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new main_layout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
